"""initial schema

Revision ID: f891a47580ab
Revises: 
Create Date: 2026-04-15 21:38:31.091308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f891a47580ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medico',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_medico')
    )
    op.create_table('red_apoyo',
    sa.Column('id_apoyo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=True),
    sa.Column('relacion', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_apoyo'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('sintoma',
    sa.Column('id_sintoma', sa.Integer(), nullable=False),
    sa.Column('nombre_sintoma', sa.String(length=100), nullable=False),
    sa.Column('severidad', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_sintoma')
    )
    op.create_table('evento_medical',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('estado_evento', sa.String(length=30), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id_medico'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('tamano_actual', sa.String(length=10), nullable=True),
    sa.Column('ficha_clinica', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('peso_actual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id_apoyo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_apoyo'], ['red_apoyo.id_apoyo'], ),
    sa.PrimaryKeyConstraint('id_paciente'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('estado_diario',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('adherencia', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tamano', sa.String(), nullable=True),
    sa.Column('animo', sa.Integer(), nullable=True),
    sa.Column('motivacion', sa.Integer(), nullable=True),
    sa.Column('alerta_riesgo_tratamiento', sa.Integer(), nullable=True),
    sa.Column('alerta_riesgo_abandono', sa.Integer(), nullable=True),
    sa.Column('imc', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.CheckConstraint('adherencia BETWEEN 0 AND 1', name='ck_estado_adherencia'),
    sa.CheckConstraint('alerta_riesgo_abandono BETWEEN 1 AND 5', name='ck_estado_alerta_abandono'),
    sa.CheckConstraint('alerta_riesgo_tratamiento BETWEEN 1 AND 5', name='ck_estado_alerta_tratamiento'),
    sa.CheckConstraint('animo BETWEEN 1 AND 5', name='ck_estado_animo'),
    sa.CheckConstraint('motivacion BETWEEN 1 AND 5', name='ck_estado_motivacion'),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_estado')
    )
    op.create_table('interaccion',
    sa.Column('id_interaccion', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('emisor', sa.String(length=50), nullable=False),
    sa.Column('tipo_mensaje', sa.String(length=50), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('feedback_paciente', sa.Text(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_interaccion')
    )
    op.create_table('paciente_evento',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['evento_medical.id_evento'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_paciente', 'id_evento')
    )
    op.create_table('paciente_medico',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id_medico'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_paciente', 'id_medico')
    )
    op.create_table('preferencias',
    sa.Column('id_preferencia', sa.Integer(), nullable=False),
    sa.Column('tipo_preferencia', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_preferencia')
    )
    op.create_table('estado_sintoma',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('id_sintoma', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estado_diario.id_estado'], ),
    sa.ForeignKeyConstraint(['id_sintoma'], ['sintoma.id_sintoma'], ),
    sa.PrimaryKeyConstraint('id_estado', 'id_sintoma')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estado_sintoma')
    op.drop_table('preferencias')
    op.drop_table('paciente_medico')
    op.drop_table('paciente_evento')
    op.drop_table('interaccion')
    op.drop_table('estado_diario')
    op.drop_table('paciente')
    op.drop_table('evento_medical')
    op.drop_table('sintoma')
    op.drop_table('red_apoyo')
    op.drop_table('medico')
    # ### end Alembic commands ###
